export const SELL_ERROR_STATUSES: Record<string, number> = {
  INVALID_OUTCOME: 400,
  MARKET_NOT_FOUND: 404,
  MARKET_CLOSED: 409,
  MARKET_INACTIVE: 409,
  PRICE_UNAVAILABLE: 409,
  POSITION_NOT_FOUND: 404,
  POSITION_GROUP_NOT_FOUND: 404,
  POSITION_NOT_OWNED: 403,
  POSITION_NOT_OPEN: 409,
  NO_AVAILABLE_SHARES: 409,
  POSITION_CONFLICT: 409
};
